#  Discretizating Features

You have a numerical feature and want to break it up into discrete bins

Depending on how we want to break up the data, there are two techniques we can
use. First, we can binarize the feature according to some threshold:

In [13]:
# Load libraries
import numpy as np
from sklearn.preprocessing import Binarizer
# Create feature
age = np.array([[6],
 [12],
 [20],
 [36],
 [65]])

In [14]:
age

array([[ 6],
       [12],
       [20],
       [36],
       [65]])

In [15]:
# Create binarizer
binarizer = Binarizer(threshold=18)

In [16]:
binarizer.fit_transform(age)

array([[0],
       [0],
       [1],
       [1],
       [1]])

Second, we can break up numerical features according to multiple thresholds

In [17]:
np.digitize(age, bins=[20,30,64])

array([[0],
       [0],
       [1],
       [2],
       [3]], dtype=int64)

In [19]:
# Bin feature
np.digitize(age, bins=[18])

array([[0],
       [0],
       [1],
       [1],
       [1]], dtype=int64)