# Generating Polynomial and Interaction Features

In [1]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

In [2]:
features = np.array([[2, 3],
 [2, 3],
[2, 3]])

In [3]:
features

array([[2, 3],
       [2, 3],
       [2, 3]])

In [4]:
polynomial_interaction = PolynomialFeatures(degree=2, include_bias=False)

In [5]:
polynomial_interaction.fit_transform(features)

array([[2., 3., 4., 6., 9.],
       [2., 3., 4., 6., 9.],
       [2., 3., 4., 6., 9.]])

### The degree parameter determines the maximum degree of the polynomial. For example, degree=2 will create new features raised to the second power:
> ### x1, x2, x1^2, x2^2

### while degree=3 will create new features raised to the second and third power:
> ### x1, x2, x1^2, x2^2, x1^3, x2^3


Furthermore, by default PolynomialFeatures includes interaction features:

> x1x2

We can restrict the features created to only interaction features by setting interac
tion_only to True:

In [7]:
interaction = PolynomialFeatures(degree=2,
 interaction_only=True, include_bias=False)
interaction.fit_transform(features)

array([[2., 3., 6.],
       [2., 3., 6.],
       [2., 3., 6.]])

Additionally, often we run into situations where the effect of one feature is dependent
on another feature. A simple example would be if we were trying to predict whether
or not our coffee was sweet and we had two features: 1) whether or not the coffee was
stirred and 2) if we added sugar. Individually, each feature does not predict coffee
sweetness, but the combination of their effects does. That is, a coffee would only be
sweet if the coffee had sugar and was stirred. The effects of each feature on the target
(sweetness) are dependent on each other. We can encode that relationship by includ‐
ing an interaction feature that is the product of the individual features.