In [1]:
import numpy as np

In [2]:
import sklearn

In [4]:
myarr = np.array([3,6,33,3])

In [5]:
myarr

array([ 3,  6, 33,  3])

In [6]:
myarr[0]

3

In [7]:
myarr.shape

(4,)

In [8]:
myarr.dtype

dtype('int64')

In [9]:
listarray = np.array([[1,2,3],[2,3,4],[3,4,5]])

In [10]:
listarray

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [11]:
listarray.size

9

In [12]:
np.array({1,2,4})

array({1, 2, 4}, dtype=object)

In [14]:
zeros = np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
rng = np.arange(15)

In [20]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
lspace = np.linspace(1,100,10)

In [24]:
lspace

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [25]:
emp = np.empty((4,))

In [26]:
emp

array([1.48e-323, 2.96e-323, 1.63e-322, 1.48e-323])

In [27]:
temp = np.empty_like(lspace)

In [30]:
ide = np.identity(3)

In [31]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
arr = np.arange(99)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [36]:
arr = arr.ravel()

In [37]:
x =[[1,2,3],[4,5,6],[7,1,0]]

In [38]:
arr = np.array(x)

In [39]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [40]:
arr.sum(axis=0)

array([12,  8,  9])

In [41]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [42]:
a = np.array([1,2,3])

In [44]:
a.sum(axis=0)

6

In [46]:
print(arr.flat)

In [47]:
arr.ndim

2

In [48]:
arr.size

9

In [49]:
arr.nbytes

72

In [50]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [51]:
a.argmax()

2

In [52]:
a

array([1, 2, 3])

In [53]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [54]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [55]:
arr2 = arr.T

In [56]:
arr + arr2

array([[ 2,  6, 10],
       [ 6, 10,  7],
       [10,  7,  0]])

In [57]:
arr * arr2

array([[ 1,  8, 21],
       [ 8, 25,  6],
       [21,  6,  0]])

In [58]:
arr - arr2

array([[ 0, -2, -4],
       [ 2,  0,  5],
       [ 4, -5,  0]])

In [59]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [60]:
arr.max()

7

In [63]:
np.where(arr>5)

(array([1, 2]), array([2, 0]))

In [65]:
np.count_nonzero(arr)

8

In [66]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [67]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))